---
title: "Candidate tweets for conjoint experiment"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
---


#List of tweet text

##The below are generated by looking at anger words >= 4

- `The last major government shutdown cost us BILLIONS. It was bad for our economy. Bad for our stability. Bad for working families. Bad for our country’s reputation.This will be the THIRD shutdown in a year.Quit playing games. End this shutdown. https://t.co/ErbmtUnA67`

- `We know it’s hot.COVID doesn’t care.Wear a mask.Not around your chin. Feeling hot is bad — COVID is worse.`

- `Restaurants may survive fear of COVID but will they survive fear of mob violence? https://t.co/YdTalPgQud`

- `I’m sure that everyone who is sick, out of work, going hungry, losing their homes, shuttering small businesses, or struggling in a zillion other ways during this pandemic is thrilled that you are hard at work to steal a Supreme Court seat for rich and powerful extremists. https://t.co/NtPkz0hrvo`

- `As the COVID-19 pandemic continues to rage and Americans are taking to the streets to express their anger at police violence and racial injustice, Leader McConnell and Senate Republicans must focus on the national crises at our doorstep. https://t.co/MsmyLf844x`

- `There has been a complete shutdown of COVID relief by the Senate GOP. But they can move with lightning speed to ram through an illegitimate Court nomination. https://t.co/PM8hDmdM9l`

- `Nine weeks since HEROES Act; delay and confusion since; dissension and dysfunction now; this is not governance — this is Republican incompetence and disarray at disgraceful levels, all with a pandemic swirling. Pathetic.`

- `China’s Communist Party lied to the world about how the coronavirus virus spread from Wuhan. They wreaked death and havoc on millions of families.  They destroyed American businesses and jobs.  No longer will the malevolent regime be able to escape justice in our courts.`

- `These high rates of COVID-19 infection &amp; mortality are driven by health &amp; economic systems that were built on foundations of abuse, discrimination, racism, and neglect that continue to hurt communities of color today.`

- `Destroying these options when #VA07 needs them the most is reckless. It's a slap in the face to our fundamental values of looking out for our neighbors &amp; protecting the vulnerable. I will keep fighting to expand access to affordable healthcare coverage, during COVID-19 &amp; beyond.`

- `Trump's reckless response to this pandemic is an impeachable offense. Given that Trump is a direct and serious threat to our public health and safety, the House should impeach him again. And, this time the Senate must remove him. @FSFP #ImpeachTrumpAgain`

- `Endless lockdown is not an option. Endless unemployment payments are not an option. Leaving children school-less for a year is not an option. And pretending that these things represent responsible policy options is a lie.`

- `I continue to hear from many constituents about the unconscionable shortage of coronavirus tests. This shortage is completely unacceptable and I share your frustration and anger.  I have spoken to the Administration to make that clear.`

- `The coronavirus has been a nuclear bomb to our economy. Workers are hurting. Small businesses are hurting. Thousands of Americans are sick.Americans are pitching in to help and I will vote yes on the #CARESAct to provide real relief NOW!https://t.co/yEmpeGrrFp`

- `Never forget: republicans have spent 10 straight years seeking to destroy the ACA.They are in court *right now* trying to steal your health care during a pandemic and lying about it.Because the republican party doesn’t give a damn if you live or die. https://t.co/BycaWeX9vJ`

- `Absolutely despicable. Countless Black prisoners are effectively being sentenced to death due to COVID-19 and unsuitable prison conditions, while Trump's former fixer gets to serve the rest of his sentence in his slippers. https://t.co/B1NIeZB4Cr`

- `In this moment, our biggest common enemy is COVID-19 and its disastrous effects on our communities. I and my colleagues are urging the Trump administration to tackle this threat with every resource at our disposal. We must act now. https://t.co/IKY0H2kxme`

- `4/Instead, small business owners — many of whom are minority and have struggled to survive the COVID-19 outbreak — now face even greater challenges due to the plunder of their businesses by professional anarchists and those motivated to do destruction by the force of Evil.`

- `The country wants justice. The people want peace, reform, progress. They reject violence.Trump wants division. He celebrates brutality. He incites violence.Above all, Trump does not want to talk about his failure to keep Americans safe amid a pandemic that has killed 182,000.`

- `I am absolutely FURIOUS at how Trump has handled our coronavirus crisis.  Now he wants to delay desperately needed payment checks until he can sign his name to the bottom.People are dying from this disease!!  We need leadership now!!   #DeposittThePeoplesMoneyNOW https://t.co/4lyPO7GeIc`

- `.@SpeakerPelosi choosing to victim blame and insinuate anyone who gets COVID is irresponsible — it’s a slap in the face to the millions who are suffering from this disease through no fault of their own. Via @juliegraceb https://t.co/9qXCYJlcjB`

- `Punishing international students during a pandemic is needlessly cruel, bad for our economy and does nothing to address the crisis at hand. Just imagine if Trump stopped exploiting #COVID19 to sow division and hate and started focusing on saving lives.https://t.co/17pXQM9VAT`

- `.@senatemajldr saying this while people are dying in a pandemic is beyond disgusting and beneath contempt. He should come to New York and tell every single one of our teachers, police officers, and firefighters why they don’t deserve our support. https://t.co/57t1x02EFv`

- `Dr. Fauci, this nationwide shutdown is not just “inconvenient” to Americans, it’s absolutely devastating.The physical and emotional toll from this self-imposed economic destruction will be worse than the doomsday prophets projected. @RepAndyBiggsAZ https://t.co/4ledwJ4GKr`

- `Small businesses would be put on their death beds with Speaker Pelosi's version of coronavirus relief. Instead of passing the Senate cure, @SpeakerPelosi is holding small biz hostage in order to sneak in numerous liberal riders at a time when Americans are hurting. Shameful.`

- `This is pretty low. After pursuing another failed impeachment — as the President was leading our national response to coronavirus — Democrats immediately began pouring money into negative attack ads. All politics, all the time.  Resistance. Obstruction. We will succeed anyway! https://t.co/fFYf5ZP92I`

- `In the middle of a pandemic, POTUS &amp; the GOP want to:<U+274C> Kick Americans off their coverage<U+274C> Allow discrimination based on pre-existing conditions<U+274C> Bring back the age tax when we know COVID-19 is more deadly for seniorsThis is beyond cruel and will cost lives. https://t.co/8pfNpYfvlL`

- `Forcing COVID patients into nursing homes &amp; killing 6,000+ seniors is bad enough.What's even worse: Covering it up.Cuomo STILL refuses to release which facilities were impacted by his deadly order.Enough dodging. Victims' families deserve the truth. https://t.co/HxZb8qjvJP`

- `Disgusting. Cuomo’s latest “report” is just another attempt to cover up the deadly outcome of his own decision to force COVID-19 patients into nursing homes.This from the same man who is still trying to blame the workers who cared for these seniors.He has no shame. https://t.co/je5qEJki6H`

- `On Thursday, @DonaldJTrumpJr said deaths are "down to almost nothing."2,236+ Americans have died of COVID-19 since then. COVID-19 is currently the third leading cause of death in the United States.No integrity. No decency. Just lie after lie after lie.https://t.co/wWr6beUtME`

- `We need bold action that addresses the full scope of the #covid crisis: sky-high unemployment, millions facing eviction and a raging deadly pandemic. These are big problems and they demand big solutions. Now isn't the time for insufficient half measures.`

- `As the President continues to promote the myth that “everyone is lying” about the virus this morning, a 30-year-old man in Texas just died after attending a “Covid party.” Among his dying words were “I think I made a mistake. I thought this was a hoax.” https://t.co/y0X6rTrpNh`

- `We can’t sit by as Donald Trump and Republicans use COVID-19 as an excuse to disenfranchise voters. We need to ensure people have the opportunity to vote by mail, early vote, vote absentee and, in every way possible, safely vote in person this November. https://t.co/uKRyR3LVTA`

- `This is a new low. As we hit 6 mil Covid cases and schools around the country are reopening, @FEMA is cutting off states from PPE? @realDonaldTrump, we can’t bear any more of your cruelty and incompetence. Stop this deadly and stupid decision, now. https://t.co/jKcSag07W5`

- `.@SenMcSallyAZ &amp; I are introducing the Stop COVID Act to make China liable for unleashing COVID-19 on our country. Americans victimized by Chinese Communist Party lies &amp; deceit deserve the opportunity to take China to court in the U.S. &amp; demand compensation. @LanceGooden`

- `Let me be as clear as I can. For 10 yrs state republicans have blocked Medicaid expansion, heaping untold misery onto their neighbors.During the pandemic their cruelty is catastrophically disastrous.Americans are dying bc republicans wanted to spite Pres. Obama &amp; the ACA. https://t.co/mUsywj7WQU`

- `A partisan lawsuit to take away health care from 23 million Americans during the best of times is reckless and dangerous. Doing so during a pandemic is immoral and deadly.We must fight for greater access to quality, affordable health care--not less. https://t.co/QoWAkaRbEN`

- `Trump accuses frontline medical heroes fighting to keep us safe of fraud and tries to erase the loss of Americans who died in the pandemic — all in a pathetic attempt to make his own incompetence seem less horrific than it is. Just disgusting. https://t.co/1qoT4BtGWR`

- `Enough with this bogus claim, you idiot. The cause of death is what actually caused your death. If you had COVID and walked outside and got hit by a bus, the cause of death wouldn’t be the virus, it would be the bus. Stop shamelessly attacking our doctors, nurses, and hospitals. https://t.co/YeRvQRkbQh`